### ISSUE TITLE
Read artifacts from config.yml

### ISSUE THREAD

**Issue by maxkoryukov** [maxkoryukov/pipelines-deploy-bitbucket#1]
Pipelines has its own config `bitbucket-pipelines.yml`, and it is possible to read the configuration of artifacts from one of the nodes.

sample config:

```yaml
---
image: python:2.7
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements-dev.txt -q
          - pip install -r requirements.txt -t libs -q

          - pip --version
          - flake8 --version
          - pytest --version

          - pytest
          - flake8
          - ./PipelinesDeployBitbucket.py
  tags:
    '**':
      - step:
          script:
            - pip --version
            - pip install -r requirements-dev.txt -q
            - ./PipelinesDeployBitbucket.py
      - deploy: # THIS IS CUSTOM PART!!!!
          artifacts:
            - DEFINE_THE_CONFIG_FOR_DEPLOYMENT
...
```

**Comment by maxkoryukov** [comment]
closed in 1a7285a

```yaml

---
image: python:2.7
pipelines:
  default:
    - step:
        script:
          #- pip install -U tox
          - pip install -r requirements-dev.txt -q
          - pip install -r requirements.txt -t libs -q

          - pip --version
          - flake8 --version
          - pytest --version
          #- tox --version

          - PYTHONPATH=libs pytest
          - flake8
          - ./PipelinesDeployBitbucket.py
  tags:
    '**':
      - step:
          script:
            - pip --version
            - pip install -r requirements-dev.txt -q
            - ./PipelinesDeployBitbucket.py
      - deploy:
          - provider: bitbucket-downloads
            file:
              nt.py: NetworkAutotune.py
              bt.py: NetworkAutotune.py
...
```
